stages:
  - maven-build
  - docker-build
  - k8s-deploy


before_script:
  - who
  - CI_COMMIT_TAG=${CI_COMMIT_TAG}
  - echo $CI_COMMIT_TAG


maven-build:
  stage: maven-build
  only:
    - /^*_v.*$/
  tags:
    - java
  script:
    - pwd
    - mvn test


docker-build:
  stage: docker-build
  only:
    - /^*_v.*$/
  script:
    - env=${CI_COMMIT_TAG%%_*}
    - echo $env
    - rm -rf ./app && mkdir ./app
    - mvn clean package -f ./pom.xml -P $env
    - tar -zxvf ./net.onebean.sodium.web/target/server-$env.tar.gz -C ./app
    - cp $JAVA_HOME/jre/lib/security/cacerts ./app    
    - docker login nexus.onebean.net:5000 -u=admin -p='43118vu0r647VlfZaw3087d31U6ea1'
    - docker build -t nexus.onebean.net:5000/sodium:${CI_COMMIT_TAG} .
    - docker push nexus.onebean.net:5000/sodium:${CI_COMMIT_TAG}
    - docker rmi nexus.onebean.net:5000/sodium:${CI_COMMIT_TAG}
    - rm -rf ./app


k8s-deploy_dev:
  stage: k8s-deploy
  only:
    - /^dev_v.*$/
  script:
    - mkdir -p ~/.gitlab-runner
    - echo ${KUBE_CONFIG} | base64 -d > ~/.gitlab-runner/config
    - export KUBECONFIG=~/.gitlab-runner/config
    - kubectl version
    - KUBERNETES_VERSION=$CI_COMMIT_TAG
    - KUBERNETES_VERSION=${KUBERNETES_VERSION//'.'/'-'}
    - KUBERNETES_VERSION=${KUBERNETES_VERSION//'_'/'-'}
    - test='s/kubernetes_version/temp-str/g'
    - KUBERNETES_VERSION_REGULAR=${test//'temp-str'/$KUBERNETES_VERSION}
    - sed -i $KUBERNETES_VERSION_REGULAR ./deployment.yml
    - UAG_HOST=${UAG_HOST}
    - test='s/uag-host/temp-str/g'
    - UAG_HOST=${test//'temp-str'/$UAG_HOST}
    - sed -i $UAG_HOST ./deployment.yml
    - UAG_PORT=${UAG_PORT}
    - test='s/uag-port/temp-str/g'
    - UAG_PORT=${test//'temp-str'/$UAG_PORT}
    - sed -i $UAG_PORT ./deployment.yml
    - DEFAULT_VM_ARGS=${DEFAULT_VM_ARGS}
    - test='s/default_vm_args/temp-str/g'
    - DEFAULT_VM_ARGS=${test//'temp-str'/$DEFAULT_VM_ARGS}
    - sed -i $DEFAULT_VM_ARGS ./deployment.yml
    - test='s/latest/temp-str/g'
    - CI_COMMIT_TAG=${test//'temp-str'/$CI_COMMIT_TAG}
    - sed -i $CI_COMMIT_TAG ./deployment.yml
    - sed -i '/hostAliases:/ r /usr/program/host/hosts.yml' ./deployment.yml
    - kubectl apply -f deployment.yml
    - kubectl expose deployment sodium-deployment-${KUBERNETES_VERSION} --type=NodePort -n onebean-func
    - echo "成功提交部署请求到k8s，请到k8s控制台上确认镜像是否成功部署！"